version: '3'
services:
  songbird-trivia:
    image: ghcr.io/qdlmcfresh/songbird-trivia:main
    container_name: songbird-trivia
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/project/db
